spring:
  application:
    name: sc-api
  datasource:
    url: jdbc:mysql://118.31.2.247:3306/sc_tmp1?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&autoReconnect=true&rewriteBatchedStatements=true
    username: sc
    password: '[X(anMzBq12Uad9Plj1FJxbC'
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 118.31.2.247
    port: 6379
    password: EUcU4gy$2pFlubmr@5EhOQH1
  http:
      multipart:
        maxFileSize: 100Mb
        maxRequestSize: 1000Mb

management:
  security:
    enabled: false

security:
  basic:
    enabled: false

mybatis:
  config-location: classpath:mybatis-config-new1.xml

wechat:
  app-id: wx2c6846667d3fd5bd
  app-secret: 17123f8d7cc0b5220e69e87791ea9fe4
  merchant-id:
  api-key:

qq:
  app-id: 1106365954

weibo:
  app-key: 452487483

sms:
  app-key: 20175bd54e0707
  secret: testapi@wifiabc.cn

dysms:
  access-key-id: LTAIcNSlftSWj6PJ
  access-key-secret: megtyaJbLIF9CVbgsTwwfkoAtBKB4H

debug:
  enabled: true

storeconfig:
  storepath: /data/sc
