package com.sc.repository.example;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ScAppUserExample {
    /**
     * RudderFramework框架生成代码，请不要直接修改.
     * 
     * This field corresponds to the database table sc_app_user
     * @generated 2017年12月27日 04:27:17
     */
    protected String orderByClause;

    /**
     * RudderFramework框架生成代码，请不要直接修改.
     * 
     * This field corresponds to the database table sc_app_user
     * @generated 2017年12月27日 04:27:17
     */
    protected boolean distinct;

    /**
     * RudderFramework框架生成代码，请不要直接修改.
     * 
     * This field corresponds to the database table sc_app_user
     * @generated 2017年12月27日 04:27:17
     */
    protected List<Criteria> oredCriteria;

    private int startRow;

    private int pageSize;

    /**
     *  RudderFramework框架生成代码，请不要直接修改..
     *  sc_app_user
     * @generated 2017年12月27日 04:27:17
     */
    public ScAppUserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     *  RudderFramework框架生成代码，请不要直接修改..
     *  sc_app_user
     * @generated 2017年12月27日 04:27:17
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     *  RudderFramework框架生成代码，请不要直接修改..
     *  sc_app_user
     * @generated 2017年12月27日 04:27:17
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     *  RudderFramework框架生成代码，请不要直接修改..
     *  sc_app_user
     * @generated 2017年12月27日 04:27:17
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     *  RudderFramework框架生成代码，请不要直接修改..
     *  sc_app_user
     * @generated 2017年12月27日 04:27:17
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     *  RudderFramework框架生成代码，请不要直接修改..
     *  sc_app_user
     * @generated 2017年12月27日 04:27:17
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     *  RudderFramework框架生成代码，请不要直接修改..
     *  sc_app_user
     * @generated 2017年12月27日 04:27:17
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     *  RudderFramework框架生成代码，请不要直接修改..
     *  sc_app_user
     * @generated 2017年12月27日 04:27:17
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     *  RudderFramework框架生成代码，请不要直接修改..
     *  sc_app_user
     * @generated 2017年12月27日 04:27:17
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     *  RudderFramework框架生成代码，请不要直接修改..
     *  sc_app_user
     * @generated 2017年12月27日 04:27:17
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     *  RudderFramework框架生成代码，请不要直接修改..
     *  sc_app_user
     * @generated 2017年12月27日 04:27:17
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public void setStartRow(int startRow) {
        this.startRow = startRow;
    }

    public void setPageSize(int pageSize) {
        this.pageSize = pageSize;
    }

    public int getStartRow() {
        return this.startRow;
    }

    public int getPageSize() {
        return this.pageSize;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sc_app_user
     * @generated 2017年12月27日 04:27:17
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberIsNull() {
            addCriterion("phone_number is null");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberIsNotNull() {
            addCriterion("phone_number is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberEqualTo(String value) {
            addCriterion("phone_number =", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberNotEqualTo(String value) {
            addCriterion("phone_number <>", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberGreaterThan(String value) {
            addCriterion("phone_number >", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberGreaterThanOrEqualTo(String value) {
            addCriterion("phone_number >=", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberLessThan(String value) {
            addCriterion("phone_number <", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberLessThanOrEqualTo(String value) {
            addCriterion("phone_number <=", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberLike(String value) {
            addCriterion("phone_number like", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberNotLike(String value) {
            addCriterion("phone_number not like", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberIn(List<String> values) {
            addCriterion("phone_number in", values, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberNotIn(List<String> values) {
            addCriterion("phone_number not in", values, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberBetween(String value1, String value2) {
            addCriterion("phone_number between", value1, value2, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberNotBetween(String value1, String value2) {
            addCriterion("phone_number not between", value1, value2, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andDeveloerCodeIsNull() {
            addCriterion("develoer_code is null");
            return (Criteria) this;
        }

        public Criteria andDeveloerCodeIsNotNull() {
            addCriterion("develoer_code is not null");
            return (Criteria) this;
        }

        public Criteria andDeveloerCodeEqualTo(String value) {
            addCriterion("develoer_code =", value, "develoerCode");
            return (Criteria) this;
        }

        public Criteria andDeveloerCodeNotEqualTo(String value) {
            addCriterion("develoer_code <>", value, "develoerCode");
            return (Criteria) this;
        }

        public Criteria andDeveloerCodeGreaterThan(String value) {
            addCriterion("develoer_code >", value, "develoerCode");
            return (Criteria) this;
        }

        public Criteria andDeveloerCodeGreaterThanOrEqualTo(String value) {
            addCriterion("develoer_code >=", value, "develoerCode");
            return (Criteria) this;
        }

        public Criteria andDeveloerCodeLessThan(String value) {
            addCriterion("develoer_code <", value, "develoerCode");
            return (Criteria) this;
        }

        public Criteria andDeveloerCodeLessThanOrEqualTo(String value) {
            addCriterion("develoer_code <=", value, "develoerCode");
            return (Criteria) this;
        }

        public Criteria andDeveloerCodeLike(String value) {
            addCriterion("develoer_code like", value, "develoerCode");
            return (Criteria) this;
        }

        public Criteria andDeveloerCodeNotLike(String value) {
            addCriterion("develoer_code not like", value, "develoerCode");
            return (Criteria) this;
        }

        public Criteria andDeveloerCodeIn(List<String> values) {
            addCriterion("develoer_code in", values, "develoerCode");
            return (Criteria) this;
        }

        public Criteria andDeveloerCodeNotIn(List<String> values) {
            addCriterion("develoer_code not in", values, "develoerCode");
            return (Criteria) this;
        }

        public Criteria andDeveloerCodeBetween(String value1, String value2) {
            addCriterion("develoer_code between", value1, value2, "develoerCode");
            return (Criteria) this;
        }

        public Criteria andDeveloerCodeNotBetween(String value1, String value2) {
            addCriterion("develoer_code not between", value1, value2, "develoerCode");
            return (Criteria) this;
        }

        public Criteria andTenantCodeIsNull() {
            addCriterion("tenant_code is null");
            return (Criteria) this;
        }

        public Criteria andTenantCodeIsNotNull() {
            addCriterion("tenant_code is not null");
            return (Criteria) this;
        }

        public Criteria andTenantCodeEqualTo(String value) {
            addCriterion("tenant_code =", value, "tenantCode");
            return (Criteria) this;
        }

        public Criteria andTenantCodeNotEqualTo(String value) {
            addCriterion("tenant_code <>", value, "tenantCode");
            return (Criteria) this;
        }

        public Criteria andTenantCodeGreaterThan(String value) {
            addCriterion("tenant_code >", value, "tenantCode");
            return (Criteria) this;
        }

        public Criteria andTenantCodeGreaterThanOrEqualTo(String value) {
            addCriterion("tenant_code >=", value, "tenantCode");
            return (Criteria) this;
        }

        public Criteria andTenantCodeLessThan(String value) {
            addCriterion("tenant_code <", value, "tenantCode");
            return (Criteria) this;
        }

        public Criteria andTenantCodeLessThanOrEqualTo(String value) {
            addCriterion("tenant_code <=", value, "tenantCode");
            return (Criteria) this;
        }

        public Criteria andTenantCodeLike(String value) {
            addCriterion("tenant_code like", value, "tenantCode");
            return (Criteria) this;
        }

        public Criteria andTenantCodeNotLike(String value) {
            addCriterion("tenant_code not like", value, "tenantCode");
            return (Criteria) this;
        }

        public Criteria andTenantCodeIn(List<String> values) {
            addCriterion("tenant_code in", values, "tenantCode");
            return (Criteria) this;
        }

        public Criteria andTenantCodeNotIn(List<String> values) {
            addCriterion("tenant_code not in", values, "tenantCode");
            return (Criteria) this;
        }

        public Criteria andTenantCodeBetween(String value1, String value2) {
            addCriterion("tenant_code between", value1, value2, "tenantCode");
            return (Criteria) this;
        }

        public Criteria andTenantCodeNotBetween(String value1, String value2) {
            addCriterion("tenant_code not between", value1, value2, "tenantCode");
            return (Criteria) this;
        }

        public Criteria andProxyUserIsNull() {
            addCriterion("proxy_user is null");
            return (Criteria) this;
        }

        public Criteria andProxyUserIsNotNull() {
            addCriterion("proxy_user is not null");
            return (Criteria) this;
        }

        public Criteria andProxyUserEqualTo(String value) {
            addCriterion("proxy_user =", value, "proxyUser");
            return (Criteria) this;
        }

        public Criteria andProxyUserNotEqualTo(String value) {
            addCriterion("proxy_user <>", value, "proxyUser");
            return (Criteria) this;
        }

        public Criteria andProxyUserGreaterThan(String value) {
            addCriterion("proxy_user >", value, "proxyUser");
            return (Criteria) this;
        }

        public Criteria andProxyUserGreaterThanOrEqualTo(String value) {
            addCriterion("proxy_user >=", value, "proxyUser");
            return (Criteria) this;
        }

        public Criteria andProxyUserLessThan(String value) {
            addCriterion("proxy_user <", value, "proxyUser");
            return (Criteria) this;
        }

        public Criteria andProxyUserLessThanOrEqualTo(String value) {
            addCriterion("proxy_user <=", value, "proxyUser");
            return (Criteria) this;
        }

        public Criteria andProxyUserLike(String value) {
            addCriterion("proxy_user like", value, "proxyUser");
            return (Criteria) this;
        }

        public Criteria andProxyUserNotLike(String value) {
            addCriterion("proxy_user not like", value, "proxyUser");
            return (Criteria) this;
        }

        public Criteria andProxyUserIn(List<String> values) {
            addCriterion("proxy_user in", values, "proxyUser");
            return (Criteria) this;
        }

        public Criteria andProxyUserNotIn(List<String> values) {
            addCriterion("proxy_user not in", values, "proxyUser");
            return (Criteria) this;
        }

        public Criteria andProxyUserBetween(String value1, String value2) {
            addCriterion("proxy_user between", value1, value2, "proxyUser");
            return (Criteria) this;
        }

        public Criteria andProxyUserNotBetween(String value1, String value2) {
            addCriterion("proxy_user not between", value1, value2, "proxyUser");
            return (Criteria) this;
        }

        public Criteria andHttpServerIsNull() {
            addCriterion("http_server is null");
            return (Criteria) this;
        }

        public Criteria andHttpServerIsNotNull() {
            addCriterion("http_server is not null");
            return (Criteria) this;
        }

        public Criteria andHttpServerEqualTo(String value) {
            addCriterion("http_server =", value, "httpServer");
            return (Criteria) this;
        }

        public Criteria andHttpServerNotEqualTo(String value) {
            addCriterion("http_server <>", value, "httpServer");
            return (Criteria) this;
        }

        public Criteria andHttpServerGreaterThan(String value) {
            addCriterion("http_server >", value, "httpServer");
            return (Criteria) this;
        }

        public Criteria andHttpServerGreaterThanOrEqualTo(String value) {
            addCriterion("http_server >=", value, "httpServer");
            return (Criteria) this;
        }

        public Criteria andHttpServerLessThan(String value) {
            addCriterion("http_server <", value, "httpServer");
            return (Criteria) this;
        }

        public Criteria andHttpServerLessThanOrEqualTo(String value) {
            addCriterion("http_server <=", value, "httpServer");
            return (Criteria) this;
        }

        public Criteria andHttpServerLike(String value) {
            addCriterion("http_server like", value, "httpServer");
            return (Criteria) this;
        }

        public Criteria andHttpServerNotLike(String value) {
            addCriterion("http_server not like", value, "httpServer");
            return (Criteria) this;
        }

        public Criteria andHttpServerIn(List<String> values) {
            addCriterion("http_server in", values, "httpServer");
            return (Criteria) this;
        }

        public Criteria andHttpServerNotIn(List<String> values) {
            addCriterion("http_server not in", values, "httpServer");
            return (Criteria) this;
        }

        public Criteria andHttpServerBetween(String value1, String value2) {
            addCriterion("http_server between", value1, value2, "httpServer");
            return (Criteria) this;
        }

        public Criteria andHttpServerNotBetween(String value1, String value2) {
            addCriterion("http_server not between", value1, value2, "httpServer");
            return (Criteria) this;
        }

        public Criteria andSmUnidIsNull() {
            addCriterion("sm_unid is null");
            return (Criteria) this;
        }

        public Criteria andSmUnidIsNotNull() {
            addCriterion("sm_unid is not null");
            return (Criteria) this;
        }

        public Criteria andSmUnidEqualTo(String value) {
            addCriterion("sm_unid =", value, "smUnid");
            return (Criteria) this;
        }

        public Criteria andSmUnidNotEqualTo(String value) {
            addCriterion("sm_unid <>", value, "smUnid");
            return (Criteria) this;
        }

        public Criteria andSmUnidGreaterThan(String value) {
            addCriterion("sm_unid >", value, "smUnid");
            return (Criteria) this;
        }

        public Criteria andSmUnidGreaterThanOrEqualTo(String value) {
            addCriterion("sm_unid >=", value, "smUnid");
            return (Criteria) this;
        }

        public Criteria andSmUnidLessThan(String value) {
            addCriterion("sm_unid <", value, "smUnid");
            return (Criteria) this;
        }

        public Criteria andSmUnidLessThanOrEqualTo(String value) {
            addCriterion("sm_unid <=", value, "smUnid");
            return (Criteria) this;
        }

        public Criteria andSmUnidLike(String value) {
            addCriterion("sm_unid like", value, "smUnid");
            return (Criteria) this;
        }

        public Criteria andSmUnidNotLike(String value) {
            addCriterion("sm_unid not like", value, "smUnid");
            return (Criteria) this;
        }

        public Criteria andSmUnidIn(List<String> values) {
            addCriterion("sm_unid in", values, "smUnid");
            return (Criteria) this;
        }

        public Criteria andSmUnidNotIn(List<String> values) {
            addCriterion("sm_unid not in", values, "smUnid");
            return (Criteria) this;
        }

        public Criteria andSmUnidBetween(String value1, String value2) {
            addCriterion("sm_unid between", value1, value2, "smUnid");
            return (Criteria) this;
        }

        public Criteria andSmUnidNotBetween(String value1, String value2) {
            addCriterion("sm_unid not between", value1, value2, "smUnid");
            return (Criteria) this;
        }

        public Criteria andSmUserNameIsNull() {
            addCriterion("sm_user_name is null");
            return (Criteria) this;
        }

        public Criteria andSmUserNameIsNotNull() {
            addCriterion("sm_user_name is not null");
            return (Criteria) this;
        }

        public Criteria andSmUserNameEqualTo(String value) {
            addCriterion("sm_user_name =", value, "smUserName");
            return (Criteria) this;
        }

        public Criteria andSmUserNameNotEqualTo(String value) {
            addCriterion("sm_user_name <>", value, "smUserName");
            return (Criteria) this;
        }

        public Criteria andSmUserNameGreaterThan(String value) {
            addCriterion("sm_user_name >", value, "smUserName");
            return (Criteria) this;
        }

        public Criteria andSmUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("sm_user_name >=", value, "smUserName");
            return (Criteria) this;
        }

        public Criteria andSmUserNameLessThan(String value) {
            addCriterion("sm_user_name <", value, "smUserName");
            return (Criteria) this;
        }

        public Criteria andSmUserNameLessThanOrEqualTo(String value) {
            addCriterion("sm_user_name <=", value, "smUserName");
            return (Criteria) this;
        }

        public Criteria andSmUserNameLike(String value) {
            addCriterion("sm_user_name like", value, "smUserName");
            return (Criteria) this;
        }

        public Criteria andSmUserNameNotLike(String value) {
            addCriterion("sm_user_name not like", value, "smUserName");
            return (Criteria) this;
        }

        public Criteria andSmUserNameIn(List<String> values) {
            addCriterion("sm_user_name in", values, "smUserName");
            return (Criteria) this;
        }

        public Criteria andSmUserNameNotIn(List<String> values) {
            addCriterion("sm_user_name not in", values, "smUserName");
            return (Criteria) this;
        }

        public Criteria andSmUserNameBetween(String value1, String value2) {
            addCriterion("sm_user_name between", value1, value2, "smUserName");
            return (Criteria) this;
        }

        public Criteria andSmUserNameNotBetween(String value1, String value2) {
            addCriterion("sm_user_name not between", value1, value2, "smUserName");
            return (Criteria) this;
        }

        public Criteria andSmUserLoginNameIsNull() {
            addCriterion("sm_user_login_name is null");
            return (Criteria) this;
        }

        public Criteria andSmUserLoginNameIsNotNull() {
            addCriterion("sm_user_login_name is not null");
            return (Criteria) this;
        }

        public Criteria andSmUserLoginNameEqualTo(String value) {
            addCriterion("sm_user_login_name =", value, "smUserLoginName");
            return (Criteria) this;
        }

        public Criteria andSmUserLoginNameNotEqualTo(String value) {
            addCriterion("sm_user_login_name <>", value, "smUserLoginName");
            return (Criteria) this;
        }

        public Criteria andSmUserLoginNameGreaterThan(String value) {
            addCriterion("sm_user_login_name >", value, "smUserLoginName");
            return (Criteria) this;
        }

        public Criteria andSmUserLoginNameGreaterThanOrEqualTo(String value) {
            addCriterion("sm_user_login_name >=", value, "smUserLoginName");
            return (Criteria) this;
        }

        public Criteria andSmUserLoginNameLessThan(String value) {
            addCriterion("sm_user_login_name <", value, "smUserLoginName");
            return (Criteria) this;
        }

        public Criteria andSmUserLoginNameLessThanOrEqualTo(String value) {
            addCriterion("sm_user_login_name <=", value, "smUserLoginName");
            return (Criteria) this;
        }

        public Criteria andSmUserLoginNameLike(String value) {
            addCriterion("sm_user_login_name like", value, "smUserLoginName");
            return (Criteria) this;
        }

        public Criteria andSmUserLoginNameNotLike(String value) {
            addCriterion("sm_user_login_name not like", value, "smUserLoginName");
            return (Criteria) this;
        }

        public Criteria andSmUserLoginNameIn(List<String> values) {
            addCriterion("sm_user_login_name in", values, "smUserLoginName");
            return (Criteria) this;
        }

        public Criteria andSmUserLoginNameNotIn(List<String> values) {
            addCriterion("sm_user_login_name not in", values, "smUserLoginName");
            return (Criteria) this;
        }

        public Criteria andSmUserLoginNameBetween(String value1, String value2) {
            addCriterion("sm_user_login_name between", value1, value2, "smUserLoginName");
            return (Criteria) this;
        }

        public Criteria andSmUserLoginNameNotBetween(String value1, String value2) {
            addCriterion("sm_user_login_name not between", value1, value2, "smUserLoginName");
            return (Criteria) this;
        }

        public Criteria andSmUserTypeIsNull() {
            addCriterion("sm_user_type is null");
            return (Criteria) this;
        }

        public Criteria andSmUserTypeIsNotNull() {
            addCriterion("sm_user_type is not null");
            return (Criteria) this;
        }

        public Criteria andSmUserTypeEqualTo(String value) {
            addCriterion("sm_user_type =", value, "smUserType");
            return (Criteria) this;
        }

        public Criteria andSmUserTypeNotEqualTo(String value) {
            addCriterion("sm_user_type <>", value, "smUserType");
            return (Criteria) this;
        }

        public Criteria andSmUserTypeGreaterThan(String value) {
            addCriterion("sm_user_type >", value, "smUserType");
            return (Criteria) this;
        }

        public Criteria andSmUserTypeGreaterThanOrEqualTo(String value) {
            addCriterion("sm_user_type >=", value, "smUserType");
            return (Criteria) this;
        }

        public Criteria andSmUserTypeLessThan(String value) {
            addCriterion("sm_user_type <", value, "smUserType");
            return (Criteria) this;
        }

        public Criteria andSmUserTypeLessThanOrEqualTo(String value) {
            addCriterion("sm_user_type <=", value, "smUserType");
            return (Criteria) this;
        }

        public Criteria andSmUserTypeLike(String value) {
            addCriterion("sm_user_type like", value, "smUserType");
            return (Criteria) this;
        }

        public Criteria andSmUserTypeNotLike(String value) {
            addCriterion("sm_user_type not like", value, "smUserType");
            return (Criteria) this;
        }

        public Criteria andSmUserTypeIn(List<String> values) {
            addCriterion("sm_user_type in", values, "smUserType");
            return (Criteria) this;
        }

        public Criteria andSmUserTypeNotIn(List<String> values) {
            addCriterion("sm_user_type not in", values, "smUserType");
            return (Criteria) this;
        }

        public Criteria andSmUserTypeBetween(String value1, String value2) {
            addCriterion("sm_user_type between", value1, value2, "smUserType");
            return (Criteria) this;
        }

        public Criteria andSmUserTypeNotBetween(String value1, String value2) {
            addCriterion("sm_user_type not between", value1, value2, "smUserType");
            return (Criteria) this;
        }

        public Criteria andSmCertificateNumberIsNull() {
            addCriterion("sm_certificate_number is null");
            return (Criteria) this;
        }

        public Criteria andSmCertificateNumberIsNotNull() {
            addCriterion("sm_certificate_number is not null");
            return (Criteria) this;
        }

        public Criteria andSmCertificateNumberEqualTo(String value) {
            addCriterion("sm_certificate_number =", value, "smCertificateNumber");
            return (Criteria) this;
        }

        public Criteria andSmCertificateNumberNotEqualTo(String value) {
            addCriterion("sm_certificate_number <>", value, "smCertificateNumber");
            return (Criteria) this;
        }

        public Criteria andSmCertificateNumberGreaterThan(String value) {
            addCriterion("sm_certificate_number >", value, "smCertificateNumber");
            return (Criteria) this;
        }

        public Criteria andSmCertificateNumberGreaterThanOrEqualTo(String value) {
            addCriterion("sm_certificate_number >=", value, "smCertificateNumber");
            return (Criteria) this;
        }

        public Criteria andSmCertificateNumberLessThan(String value) {
            addCriterion("sm_certificate_number <", value, "smCertificateNumber");
            return (Criteria) this;
        }

        public Criteria andSmCertificateNumberLessThanOrEqualTo(String value) {
            addCriterion("sm_certificate_number <=", value, "smCertificateNumber");
            return (Criteria) this;
        }

        public Criteria andSmCertificateNumberLike(String value) {
            addCriterion("sm_certificate_number like", value, "smCertificateNumber");
            return (Criteria) this;
        }

        public Criteria andSmCertificateNumberNotLike(String value) {
            addCriterion("sm_certificate_number not like", value, "smCertificateNumber");
            return (Criteria) this;
        }

        public Criteria andSmCertificateNumberIn(List<String> values) {
            addCriterion("sm_certificate_number in", values, "smCertificateNumber");
            return (Criteria) this;
        }

        public Criteria andSmCertificateNumberNotIn(List<String> values) {
            addCriterion("sm_certificate_number not in", values, "smCertificateNumber");
            return (Criteria) this;
        }

        public Criteria andSmCertificateNumberBetween(String value1, String value2) {
            addCriterion("sm_certificate_number between", value1, value2, "smCertificateNumber");
            return (Criteria) this;
        }

        public Criteria andSmCertificateNumberNotBetween(String value1, String value2) {
            addCriterion("sm_certificate_number not between", value1, value2, "smCertificateNumber");
            return (Criteria) this;
        }

        public Criteria andSmSexIsNull() {
            addCriterion("sm_sex is null");
            return (Criteria) this;
        }

        public Criteria andSmSexIsNotNull() {
            addCriterion("sm_sex is not null");
            return (Criteria) this;
        }

        public Criteria andSmSexEqualTo(String value) {
            addCriterion("sm_sex =", value, "smSex");
            return (Criteria) this;
        }

        public Criteria andSmSexNotEqualTo(String value) {
            addCriterion("sm_sex <>", value, "smSex");
            return (Criteria) this;
        }

        public Criteria andSmSexGreaterThan(String value) {
            addCriterion("sm_sex >", value, "smSex");
            return (Criteria) this;
        }

        public Criteria andSmSexGreaterThanOrEqualTo(String value) {
            addCriterion("sm_sex >=", value, "smSex");
            return (Criteria) this;
        }

        public Criteria andSmSexLessThan(String value) {
            addCriterion("sm_sex <", value, "smSex");
            return (Criteria) this;
        }

        public Criteria andSmSexLessThanOrEqualTo(String value) {
            addCriterion("sm_sex <=", value, "smSex");
            return (Criteria) this;
        }

        public Criteria andSmSexLike(String value) {
            addCriterion("sm_sex like", value, "smSex");
            return (Criteria) this;
        }

        public Criteria andSmSexNotLike(String value) {
            addCriterion("sm_sex not like", value, "smSex");
            return (Criteria) this;
        }

        public Criteria andSmSexIn(List<String> values) {
            addCriterion("sm_sex in", values, "smSex");
            return (Criteria) this;
        }

        public Criteria andSmSexNotIn(List<String> values) {
            addCriterion("sm_sex not in", values, "smSex");
            return (Criteria) this;
        }

        public Criteria andSmSexBetween(String value1, String value2) {
            addCriterion("sm_sex between", value1, value2, "smSex");
            return (Criteria) this;
        }

        public Criteria andSmSexNotBetween(String value1, String value2) {
            addCriterion("sm_sex not between", value1, value2, "smSex");
            return (Criteria) this;
        }

        public Criteria andSmMobilePhoneIsNull() {
            addCriterion("sm_mobile_phone is null");
            return (Criteria) this;
        }

        public Criteria andSmMobilePhoneIsNotNull() {
            addCriterion("sm_mobile_phone is not null");
            return (Criteria) this;
        }

        public Criteria andSmMobilePhoneEqualTo(String value) {
            addCriterion("sm_mobile_phone =", value, "smMobilePhone");
            return (Criteria) this;
        }

        public Criteria andSmMobilePhoneNotEqualTo(String value) {
            addCriterion("sm_mobile_phone <>", value, "smMobilePhone");
            return (Criteria) this;
        }

        public Criteria andSmMobilePhoneGreaterThan(String value) {
            addCriterion("sm_mobile_phone >", value, "smMobilePhone");
            return (Criteria) this;
        }

        public Criteria andSmMobilePhoneGreaterThanOrEqualTo(String value) {
            addCriterion("sm_mobile_phone >=", value, "smMobilePhone");
            return (Criteria) this;
        }

        public Criteria andSmMobilePhoneLessThan(String value) {
            addCriterion("sm_mobile_phone <", value, "smMobilePhone");
            return (Criteria) this;
        }

        public Criteria andSmMobilePhoneLessThanOrEqualTo(String value) {
            addCriterion("sm_mobile_phone <=", value, "smMobilePhone");
            return (Criteria) this;
        }

        public Criteria andSmMobilePhoneLike(String value) {
            addCriterion("sm_mobile_phone like", value, "smMobilePhone");
            return (Criteria) this;
        }

        public Criteria andSmMobilePhoneNotLike(String value) {
            addCriterion("sm_mobile_phone not like", value, "smMobilePhone");
            return (Criteria) this;
        }

        public Criteria andSmMobilePhoneIn(List<String> values) {
            addCriterion("sm_mobile_phone in", values, "smMobilePhone");
            return (Criteria) this;
        }

        public Criteria andSmMobilePhoneNotIn(List<String> values) {
            addCriterion("sm_mobile_phone not in", values, "smMobilePhone");
            return (Criteria) this;
        }

        public Criteria andSmMobilePhoneBetween(String value1, String value2) {
            addCriterion("sm_mobile_phone between", value1, value2, "smMobilePhone");
            return (Criteria) this;
        }

        public Criteria andSmMobilePhoneNotBetween(String value1, String value2) {
            addCriterion("sm_mobile_phone not between", value1, value2, "smMobilePhone");
            return (Criteria) this;
        }

        public Criteria andSmAddressIsNull() {
            addCriterion("sm_address is null");
            return (Criteria) this;
        }

        public Criteria andSmAddressIsNotNull() {
            addCriterion("sm_address is not null");
            return (Criteria) this;
        }

        public Criteria andSmAddressEqualTo(String value) {
            addCriterion("sm_address =", value, "smAddress");
            return (Criteria) this;
        }

        public Criteria andSmAddressNotEqualTo(String value) {
            addCriterion("sm_address <>", value, "smAddress");
            return (Criteria) this;
        }

        public Criteria andSmAddressGreaterThan(String value) {
            addCriterion("sm_address >", value, "smAddress");
            return (Criteria) this;
        }

        public Criteria andSmAddressGreaterThanOrEqualTo(String value) {
            addCriterion("sm_address >=", value, "smAddress");
            return (Criteria) this;
        }

        public Criteria andSmAddressLessThan(String value) {
            addCriterion("sm_address <", value, "smAddress");
            return (Criteria) this;
        }

        public Criteria andSmAddressLessThanOrEqualTo(String value) {
            addCriterion("sm_address <=", value, "smAddress");
            return (Criteria) this;
        }

        public Criteria andSmAddressLike(String value) {
            addCriterion("sm_address like", value, "smAddress");
            return (Criteria) this;
        }

        public Criteria andSmAddressNotLike(String value) {
            addCriterion("sm_address not like", value, "smAddress");
            return (Criteria) this;
        }

        public Criteria andSmAddressIn(List<String> values) {
            addCriterion("sm_address in", values, "smAddress");
            return (Criteria) this;
        }

        public Criteria andSmAddressNotIn(List<String> values) {
            addCriterion("sm_address not in", values, "smAddress");
            return (Criteria) this;
        }

        public Criteria andSmAddressBetween(String value1, String value2) {
            addCriterion("sm_address between", value1, value2, "smAddress");
            return (Criteria) this;
        }

        public Criteria andSmAddressNotBetween(String value1, String value2) {
            addCriterion("sm_address not between", value1, value2, "smAddress");
            return (Criteria) this;
        }

        public Criteria andSmEmailIsNull() {
            addCriterion("sm_email is null");
            return (Criteria) this;
        }

        public Criteria andSmEmailIsNotNull() {
            addCriterion("sm_email is not null");
            return (Criteria) this;
        }

        public Criteria andSmEmailEqualTo(String value) {
            addCriterion("sm_email =", value, "smEmail");
            return (Criteria) this;
        }

        public Criteria andSmEmailNotEqualTo(String value) {
            addCriterion("sm_email <>", value, "smEmail");
            return (Criteria) this;
        }

        public Criteria andSmEmailGreaterThan(String value) {
            addCriterion("sm_email >", value, "smEmail");
            return (Criteria) this;
        }

        public Criteria andSmEmailGreaterThanOrEqualTo(String value) {
            addCriterion("sm_email >=", value, "smEmail");
            return (Criteria) this;
        }

        public Criteria andSmEmailLessThan(String value) {
            addCriterion("sm_email <", value, "smEmail");
            return (Criteria) this;
        }

        public Criteria andSmEmailLessThanOrEqualTo(String value) {
            addCriterion("sm_email <=", value, "smEmail");
            return (Criteria) this;
        }

        public Criteria andSmEmailLike(String value) {
            addCriterion("sm_email like", value, "smEmail");
            return (Criteria) this;
        }

        public Criteria andSmEmailNotLike(String value) {
            addCriterion("sm_email not like", value, "smEmail");
            return (Criteria) this;
        }

        public Criteria andSmEmailIn(List<String> values) {
            addCriterion("sm_email in", values, "smEmail");
            return (Criteria) this;
        }

        public Criteria andSmEmailNotIn(List<String> values) {
            addCriterion("sm_email not in", values, "smEmail");
            return (Criteria) this;
        }

        public Criteria andSmEmailBetween(String value1, String value2) {
            addCriterion("sm_email between", value1, value2, "smEmail");
            return (Criteria) this;
        }

        public Criteria andSmEmailNotBetween(String value1, String value2) {
            addCriterion("sm_email not between", value1, value2, "smEmail");
            return (Criteria) this;
        }

        public Criteria andSmNameIsNull() {
            addCriterion("sm_name is null");
            return (Criteria) this;
        }

        public Criteria andSmNameIsNotNull() {
            addCriterion("sm_name is not null");
            return (Criteria) this;
        }

        public Criteria andSmNameEqualTo(String value) {
            addCriterion("sm_name =", value, "smName");
            return (Criteria) this;
        }

        public Criteria andSmNameNotEqualTo(String value) {
            addCriterion("sm_name <>", value, "smName");
            return (Criteria) this;
        }

        public Criteria andSmNameGreaterThan(String value) {
            addCriterion("sm_name >", value, "smName");
            return (Criteria) this;
        }

        public Criteria andSmNameGreaterThanOrEqualTo(String value) {
            addCriterion("sm_name >=", value, "smName");
            return (Criteria) this;
        }

        public Criteria andSmNameLessThan(String value) {
            addCriterion("sm_name <", value, "smName");
            return (Criteria) this;
        }

        public Criteria andSmNameLessThanOrEqualTo(String value) {
            addCriterion("sm_name <=", value, "smName");
            return (Criteria) this;
        }

        public Criteria andSmNameLike(String value) {
            addCriterion("sm_name like", value, "smName");
            return (Criteria) this;
        }

        public Criteria andSmNameNotLike(String value) {
            addCriterion("sm_name not like", value, "smName");
            return (Criteria) this;
        }

        public Criteria andSmNameIn(List<String> values) {
            addCriterion("sm_name in", values, "smName");
            return (Criteria) this;
        }

        public Criteria andSmNameNotIn(List<String> values) {
            addCriterion("sm_name not in", values, "smName");
            return (Criteria) this;
        }

        public Criteria andSmNameBetween(String value1, String value2) {
            addCriterion("sm_name between", value1, value2, "smName");
            return (Criteria) this;
        }

        public Criteria andSmNameNotBetween(String value1, String value2) {
            addCriterion("sm_name not between", value1, value2, "smName");
            return (Criteria) this;
        }

        public Criteria andSmLastUpdatetimeIsNull() {
            addCriterion("sm_last_updatetime is null");
            return (Criteria) this;
        }

        public Criteria andSmLastUpdatetimeIsNotNull() {
            addCriterion("sm_last_updatetime is not null");
            return (Criteria) this;
        }

        public Criteria andSmLastUpdatetimeEqualTo(String value) {
            addCriterion("sm_last_updatetime =", value, "smLastUpdatetime");
            return (Criteria) this;
        }

        public Criteria andSmLastUpdatetimeNotEqualTo(String value) {
            addCriterion("sm_last_updatetime <>", value, "smLastUpdatetime");
            return (Criteria) this;
        }

        public Criteria andSmLastUpdatetimeGreaterThan(String value) {
            addCriterion("sm_last_updatetime >", value, "smLastUpdatetime");
            return (Criteria) this;
        }

        public Criteria andSmLastUpdatetimeGreaterThanOrEqualTo(String value) {
            addCriterion("sm_last_updatetime >=", value, "smLastUpdatetime");
            return (Criteria) this;
        }

        public Criteria andSmLastUpdatetimeLessThan(String value) {
            addCriterion("sm_last_updatetime <", value, "smLastUpdatetime");
            return (Criteria) this;
        }

        public Criteria andSmLastUpdatetimeLessThanOrEqualTo(String value) {
            addCriterion("sm_last_updatetime <=", value, "smLastUpdatetime");
            return (Criteria) this;
        }

        public Criteria andSmLastUpdatetimeLike(String value) {
            addCriterion("sm_last_updatetime like", value, "smLastUpdatetime");
            return (Criteria) this;
        }

        public Criteria andSmLastUpdatetimeNotLike(String value) {
            addCriterion("sm_last_updatetime not like", value, "smLastUpdatetime");
            return (Criteria) this;
        }

        public Criteria andSmLastUpdatetimeIn(List<String> values) {
            addCriterion("sm_last_updatetime in", values, "smLastUpdatetime");
            return (Criteria) this;
        }

        public Criteria andSmLastUpdatetimeNotIn(List<String> values) {
            addCriterion("sm_last_updatetime not in", values, "smLastUpdatetime");
            return (Criteria) this;
        }

        public Criteria andSmLastUpdatetimeBetween(String value1, String value2) {
            addCriterion("sm_last_updatetime between", value1, value2, "smLastUpdatetime");
            return (Criteria) this;
        }

        public Criteria andSmLastUpdatetimeNotBetween(String value1, String value2) {
            addCriterion("sm_last_updatetime not between", value1, value2, "smLastUpdatetime");
            return (Criteria) this;
        }

        public Criteria andSmCertificateTypeIsNull() {
            addCriterion("sm_certificate_type is null");
            return (Criteria) this;
        }

        public Criteria andSmCertificateTypeIsNotNull() {
            addCriterion("sm_certificate_type is not null");
            return (Criteria) this;
        }

        public Criteria andSmCertificateTypeEqualTo(String value) {
            addCriterion("sm_certificate_type =", value, "smCertificateType");
            return (Criteria) this;
        }

        public Criteria andSmCertificateTypeNotEqualTo(String value) {
            addCriterion("sm_certificate_type <>", value, "smCertificateType");
            return (Criteria) this;
        }

        public Criteria andSmCertificateTypeGreaterThan(String value) {
            addCriterion("sm_certificate_type >", value, "smCertificateType");
            return (Criteria) this;
        }

        public Criteria andSmCertificateTypeGreaterThanOrEqualTo(String value) {
            addCriterion("sm_certificate_type >=", value, "smCertificateType");
            return (Criteria) this;
        }

        public Criteria andSmCertificateTypeLessThan(String value) {
            addCriterion("sm_certificate_type <", value, "smCertificateType");
            return (Criteria) this;
        }

        public Criteria andSmCertificateTypeLessThanOrEqualTo(String value) {
            addCriterion("sm_certificate_type <=", value, "smCertificateType");
            return (Criteria) this;
        }

        public Criteria andSmCertificateTypeLike(String value) {
            addCriterion("sm_certificate_type like", value, "smCertificateType");
            return (Criteria) this;
        }

        public Criteria andSmCertificateTypeNotLike(String value) {
            addCriterion("sm_certificate_type not like", value, "smCertificateType");
            return (Criteria) this;
        }

        public Criteria andSmCertificateTypeIn(List<String> values) {
            addCriterion("sm_certificate_type in", values, "smCertificateType");
            return (Criteria) this;
        }

        public Criteria andSmCertificateTypeNotIn(List<String> values) {
            addCriterion("sm_certificate_type not in", values, "smCertificateType");
            return (Criteria) this;
        }

        public Criteria andSmCertificateTypeBetween(String value1, String value2) {
            addCriterion("sm_certificate_type between", value1, value2, "smCertificateType");
            return (Criteria) this;
        }

        public Criteria andSmCertificateTypeNotBetween(String value1, String value2) {
            addCriterion("sm_certificate_type not between", value1, value2, "smCertificateType");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNull() {
            addCriterion("created_at is null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNotNull() {
            addCriterion("created_at is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtEqualTo(Date value) {
            addCriterion("created_at =", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotEqualTo(Date value) {
            addCriterion("created_at <>", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThan(Date value) {
            addCriterion("created_at >", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("created_at >=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThan(Date value) {
            addCriterion("created_at <", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThanOrEqualTo(Date value) {
            addCriterion("created_at <=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIn(List<Date> values) {
            addCriterion("created_at in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotIn(List<Date> values) {
            addCriterion("created_at not in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtBetween(Date value1, Date value2) {
            addCriterion("created_at between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotBetween(Date value1, Date value2) {
            addCriterion("created_at not between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNull() {
            addCriterion("updated_at is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNotNull() {
            addCriterion("updated_at is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtEqualTo(Date value) {
            addCriterion("updated_at =", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotEqualTo(Date value) {
            addCriterion("updated_at <>", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThan(Date value) {
            addCriterion("updated_at >", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("updated_at >=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThan(Date value) {
            addCriterion("updated_at <", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThanOrEqualTo(Date value) {
            addCriterion("updated_at <=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIn(List<Date> values) {
            addCriterion("updated_at in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotIn(List<Date> values) {
            addCriterion("updated_at not in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtBetween(Date value1, Date value2) {
            addCriterion("updated_at between", value1, value2, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotBetween(Date value1, Date value2) {
            addCriterion("updated_at not between", value1, value2, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNull() {
            addCriterion("creator is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNotNull() {
            addCriterion("creator is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorEqualTo(Long value) {
            addCriterion("creator =", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotEqualTo(Long value) {
            addCriterion("creator <>", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThan(Long value) {
            addCriterion("creator >", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThanOrEqualTo(Long value) {
            addCriterion("creator >=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThan(Long value) {
            addCriterion("creator <", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThanOrEqualTo(Long value) {
            addCriterion("creator <=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorIn(List<Long> values) {
            addCriterion("creator in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotIn(List<Long> values) {
            addCriterion("creator not in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorBetween(Long value1, Long value2) {
            addCriterion("creator between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotBetween(Long value1, Long value2) {
            addCriterion("creator not between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andLastModifierIsNull() {
            addCriterion("last_modifier is null");
            return (Criteria) this;
        }

        public Criteria andLastModifierIsNotNull() {
            addCriterion("last_modifier is not null");
            return (Criteria) this;
        }

        public Criteria andLastModifierEqualTo(Long value) {
            addCriterion("last_modifier =", value, "lastModifier");
            return (Criteria) this;
        }

        public Criteria andLastModifierNotEqualTo(Long value) {
            addCriterion("last_modifier <>", value, "lastModifier");
            return (Criteria) this;
        }

        public Criteria andLastModifierGreaterThan(Long value) {
            addCriterion("last_modifier >", value, "lastModifier");
            return (Criteria) this;
        }

        public Criteria andLastModifierGreaterThanOrEqualTo(Long value) {
            addCriterion("last_modifier >=", value, "lastModifier");
            return (Criteria) this;
        }

        public Criteria andLastModifierLessThan(Long value) {
            addCriterion("last_modifier <", value, "lastModifier");
            return (Criteria) this;
        }

        public Criteria andLastModifierLessThanOrEqualTo(Long value) {
            addCriterion("last_modifier <=", value, "lastModifier");
            return (Criteria) this;
        }

        public Criteria andLastModifierIn(List<Long> values) {
            addCriterion("last_modifier in", values, "lastModifier");
            return (Criteria) this;
        }

        public Criteria andLastModifierNotIn(List<Long> values) {
            addCriterion("last_modifier not in", values, "lastModifier");
            return (Criteria) this;
        }

        public Criteria andLastModifierBetween(Long value1, Long value2) {
            addCriterion("last_modifier between", value1, value2, "lastModifier");
            return (Criteria) this;
        }

        public Criteria andLastModifierNotBetween(Long value1, Long value2) {
            addCriterion("last_modifier not between", value1, value2, "lastModifier");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNull() {
            addCriterion("deleted is null");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNotNull() {
            addCriterion("deleted is not null");
            return (Criteria) this;
        }

        public Criteria andDeletedEqualTo(Boolean value) {
            addCriterion("deleted =", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotEqualTo(Boolean value) {
            addCriterion("deleted <>", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThan(Boolean value) {
            addCriterion("deleted >", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("deleted >=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThan(Boolean value) {
            addCriterion("deleted <", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThanOrEqualTo(Boolean value) {
            addCriterion("deleted <=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedIn(List<Boolean> values) {
            addCriterion("deleted in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotIn(List<Boolean> values) {
            addCriterion("deleted not in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedBetween(Boolean value1, Boolean value2) {
            addCriterion("deleted between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("deleted not between", value1, value2, "deleted");
            return (Criteria) this;
        }
    }

    /**
     * RudderFramework Util 生成.
     * 根据数据库表 sc_app_user
     * @generated do_not_delete_during_merge 2017年12月27日 04:27:17
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sc_app_user
     * @generated 2017年12月27日 04:27:17
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}